<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE siop_document [
<!ELEMENT siop_document (temperatures, levels, components, scenarios?)>
<!ELEMENT temperatures (temp+)>
<!ELEMENT temp EMPTY>
<!ATTLIST temp
          type (AP|BAT|USB|CHG|PA|WIFI) #REQUIRED
          default CDATA "1"
          min CDATA "1"
          max CDATA "1"
          step CDATA "1"
          init CDATA "5"
          hold CDATA "1"
          gap CDATA "0">
<!ELEMENT levels (level+)>
<!ELEMENT level EMPTY>
<!ATTLIST level
          id CDATA #REQUIRED
          temp CDATA #REQUIRED>
<!ELEMENT components (default, complex?)>
<!ELEMENT default (component+)>
<!ELEMENT complex (component+)>
<!ELEMENT component (limiter+)>
<!ATTLIST component
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED>
<!ELEMENT scenarios (scenario*, scenario_group*)>
<!ELEMENT scenario (limiter+)>
<!-- you can use below delimiter on scenario name -->
<!-- "!" : intent, ":" : package, "," : plural    -->
<!ATTLIST scenario
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED
          priority CDATA "0">
<!ELEMENT scenario_group (scenario+)>
<!ELEMENT scenario EMPTY>
<!ATTLIST scenario
          name CDATA #REQUIRED
          limiter CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
<!ELEMENT limiter EMPTY>
<!ATTLIST limiter
          name CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
]>

<siop_document>

    <overheatcontrol>
        <complex>
            <MW     formula="AP*BAT"    temp="490.450"     />
            <LTB    formula="AP*BAT"    temp="490.450"     />
            <LCD    formula="AP*BAT"    temp="470.430"     />
            <GDM    formula="AP*BAT"    temp="430.430"     />
            <GDMLTB formula="AP*BAT"    temp="450.450"     />
            <SS     formula="AP*BAT*PA" temp="590.450.650" />
        </complex>
    </overheatcontrol>

    <modelsettings>
        <sensors>
            <LTB_SENSOR type="PALM*LIGHT" />
        </sensors>
    </modelsettings>

    <components>

        <component name="AP" tempType="LRP" >
            <limiter name="CPUFreqMax" step="0" temp="350:380:450:470" value="-1:1747200:1747200:1516800" />
            <limiter name="GPUFreqMax" step="0" temp="350:380:450:470" value="-1:441:441:400"  />
            <limiter name="AppInstallDelay" value="5000" />
            <limiter name="BackgroundCpuset" temp="360" gap="20" value="-1:100:200:300" />
        </component>

        <component name="DISPLAY" tempType="LRP">
            <limiter name="Brightness" temp="390" value="-1:193:130" />
            <limiter name="LimitHrr" temp="460" value="-1:1" />
        </component>

        <component name="CP" tempType="LRP">
            <limiter name="DLThrot" temp="410" value="-1:2" />
            <limiter name="DLThrot" temp="420" value="-1:2" region="KOREA" />
            <limiter name="DLThrot" temp="420" value="-1:2" region="AMO" />
            <limiter name="DLThrot" temp="420" value="-1:2" region="OPV" />
            <limiter name="DLThrot" temp="420" value="-1:2" region="ORO" />
            <limiter name="DLThrot" temp="420" value="-1:2" region="FTM" />
            <limiter name="CpLowMode" value="-1" />
            <limiter name="SADisable" temp="420"     value="-1:1" />
        </component>

        <component name="CHG+DISPLAY" tempType="SKIN">
            <limiter name="Charging" temp="350" value="-1:70" />
        </component>

    </components>

    <scenarios>

        <scenario name="ScreenOffInCall" tempType="SKIN" priority="1" >
            <limiter name="Charging" value="70" />
        </scenario>

        <scenario name="SIPStart" tempType="LRP" priority="2" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450"         value="-1:1747200"   />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450"         value="-1:441" />
        </scenario>

        <scenario name="AppStart" tempType="LRP" priority="2" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450"         value="-1:1747200"   />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450"         value="-1:441" />
        </scenario>

        <scenario name="Badge" tempType="LRP" priority="2" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450"         value="-1:1747200"   />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450"         value="-1:441" />
        </scenario>

        <scenario name="WakeUp" tempType="LRP" priority="2" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450"         value="-1:1747200"   />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450"         value="-1:441" />
        </scenario>

        <scenario name="AppStore" tempType="LRP" >
            <limiter name="WifiTput"        temp="310:330:350:390:410:430" value="-1:150:100:50:30:10" />
            <limiter name="AppInstallDelay" temp="300"                     value="-1:3000:5000"        />
            <limiter name="Charging"        temp="310"                     value="70"                  />
        </scenario>

        <scenario name="VtCallControl" tempType="LRP" priority="1">
            <limiter name="AppInstallDelay" temp="300" value="-1:3000:5000" />
            <limiter name="Brightness"      temp="410" value="193:130"      />
            <limiter name="CameraFps"       temp="360" value="-1:1"         />
            <limiter name="CPUFreqMax" step="0" temp="300:320:450:470" value="-1:1747200:1747200:1516800" />
            <limiter name="GPUFreqMax" step="0" temp="300:320:450:470" value="-1:441:441:400" />
            <limiter name="Charging" value="20" />
        </scenario>

        <scenario name="SecVtCall" tempType="LRP" priority="1" region="INDIA">
            <limiter name="CPUFreqMax" step="0" temp="300:320:450:470" value="-1:1747200:1747200:1516800" />
            <limiter name="GPUFreqMax" step="0" temp="300:320:450:470" value="-1:441:441:400" />
            <limiter name="Charging" value="20" />
        </scenario>

        <scenario name="CameraRecording!Camera_recording,Camera_recordingDual" tempType="LRP" priority="1" >
            <limiter name="Brightness" temp="330:350:390:410:430" value="-1:255:255:193:130" />
        </scenario>

        <scenario name="CameraNight!Camera_night" tempType="LRP">
            <limiter name="CPUFreqMax" temp="450:480:500" value="-1:1747200:1305600" />
            <limiter name="GPUFreqMax" temp="420:450:500" value="-1:525:305" />
        </scenario>


        <scenario name="CameraLiveFocusPreview!Camera_preview_LiveFocusVideo" tempType="LRP">
            <limiter name="CPUFreqMax" step="0" temp="350:380:450:470" value="-1:1747200:1747200:1305600" />
            <limiter name="GPUFreqMax" step="0" temp="350:380:450:470" value="-1:441:441:305" />
            <limiter name="NpuFreqLevel" temp="380:400:450" value="0:2:3" />
        </scenario>

        <scenario name="ARemoji:com.samsung.android.aremoji" tempType="LRP" >
            <limiter name="GPUFreqMax" value="305" />
        </scenario>

        <scenario name="Navigation" tempType="LRP" >
            <limiter name="Brightness" temp="410" value="167:130" />
        </scenario>

        <scenario name="NReal" tempType="LRP" >
            <limiter name="CPUFreqMax" step="0" temp="360:380:400" value="-1:1747200:1305600"   />
            <limiter name="GPUFreqMax" step="0" temp="360:380:400" value="-1:441:305" />
            <limiter name="Brightness"	temp="380" value="201:144" />
            <limiter name="LimitHrr" temp="410" value="1" />
        </scenario>

        <scenario name="Heavyuser" tempType="LRP" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450:480"     value="-1:1747200"             />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="420:450:500" value="-1:525:305" />
        </scenario>

        <scenario name="FotaDownload:com.wssyncmldm" tempType="LRP" >
            <limiter name="Charging" value="70" />
        </scenario>

        <scenario name="RetailMode:com.samsung.android.retail.screensaver" tempType="LRP" >
            <limiter name="Charging" value="70" />
        </scenario>

        <scenario name="SecurePlaybackSmartView!SecureSmartView" tempType="LRP" priority="1">
            <limiter name="Charging"   value="70" />
        </scenario>

        <scenario name="NRmmW" tempType="(APT+APR)" >
            <limiter name="DLThrot" temp="390.390:410.410:430.430" value="-1:1:2" />
        </scenario>

        <scenario name="HighBrightness"  tempType="LRP*BAT" priority="1" region="XSG" >
            <limiter name="DLThrot" temp="440.420:450.430:470.450" value="-1:2:2" delay="0:1800:0" />
        </scenario>

        <scenario name="HighBrightness"  tempType="LRP*BAT" priority="1" region="KSA" >
            <limiter name="DLThrot" temp="440.420:450.430:470.450" value="-1:2:2" delay="0:1800:0" />
        </scenario>

        <scenario name="BrowserScenario" tempType="LRP" >
            <limiter name="TABoost"      temp="350" value="-1:1" />
        </scenario>

        <scenario name="HeavyLoadApp" tempType="SKIN" priority="1">
            <limiter name="CPUFreqMax" temp="340" value="-1:1632000:1516800:1075200:854400" />
            <limiter name="GPUFreqMax"                        value="305" />
            <limiter name="Brightness" temp="410:430:530:550" value="224:169:169:104" />
        </scenario>

        <scenario name="MultiWindow" tempType="LRP" priority="1">
            <limiter name="CPUFreqMax" step="0" temp="360" value="-1:1516800:1305600:1075200" />
        </scenario>

        <scenario name="SIPStartMW" tempType="LRP" priority="2" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="400:420"         value="-1:1747200"   />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="400:420"         value="-1:441" />
        </scenario>

        <scenario name="AppStartMW" tempType="LRP" priority="2" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="400:420"         value="-1:1747200"   />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="400:420"         value="-1:441" />
        </scenario>

        <scenario name="Dex" tempType="LRP" priority="1">
            <limiter name="CPUFreqMax" step="0" temp="360" value="-1:1747200:1747200:1075200" />
        </scenario>

        <scenario name="DexStabilizerMode" tempType="LRP" priority="4">
            <limiter name="CPUFreqMax" value="960000" />
        </scenario>

        <scenario name="SmartSwitch" tempType="LRP" >
            <limiter name="CPUFreqMax" step="0" temp="360" value="1747200:1516800:1075200" />
            <limiter name="Brightness"  temp="340" value="167:130" />
        </scenario>

        <scenario name="SmartSwitchTransfer" tempType="SKIN" priority="1" >
            <limiter name="Charging"    temp="280" value="-1:70"         />
        </scenario>

        <scenario name="SmartSwitchAppInstall" tempType="SKIN" priority="1" >
            <limiter name="Charging"    temp="280" value="-1:70"         />
        </scenario>

        <scenario name="SpkHeatControl" tempType="SKIN" priority="2">
            <limiter name="CPUFreqMax" temp="340:360:380:430" value="-1:2169600:1516800:1075200" />
            <limiter name="SpeakerControl" temp="340:360" value="-1:1" />
        </scenario>

        <scenario_group name="GameThermalCpuControl" tempType="LRP" >
            <scenario id="-7"  limiter="CPUFreqMax"                             value="1075200" />
            <scenario id="-6"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1747200:1075200" />
            <scenario id="-5"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1747200:1190400" />
            <scenario id="-4"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1747200:1305600" />
            <scenario id="-3"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1747200:1401600" />
            <scenario id="-2"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1747200:1516800" />
            <scenario id="-1"  limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1747200:1632000" />
            <scenario id="0"   limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1862400:1747200" />
            <scenario id="1"   limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:1977600:1862400" />
            <scenario id="2"   limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:2073600:1977600" />
            <scenario id="3"   limiter="CPUFreqMax" step="0" temp="370:380:400" value="-1:2169600:2073600" />
            <scenario id="4"   limiter="CPUFreqMax"                             value="-1" />
            <scenario name="BackgroundCpuset" temp="380:400:420" value="100:200:300" />
        </scenario_group>

        <scenario_group name="GameThermalGpuControl" tempType="LRP" >
            <scenario id="-3" limiter="GPUFreqMax"                             value="305" />
            <scenario id="-2" limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:400:305" />
            <scenario id="-1" limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:441:400" />
            <scenario id="0"  limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:490:441" />
            <scenario id="1"  limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:525:490" />
            <scenario id="2"  limiter="GPUFreqMax" step="0" temp="370:380:400" value="-1:587:525" />
            <scenario id="3"  limiter="GPUFreqMax"                             value="-1" />
        </scenario_group>

    </scenarios>

</siop_document>

